import { getT, type Locale } from "@/shared/lib/i18n";
import type { Course } from "@/entities/course";
import { siteConfig } from "@/shared/config/common";
import { COURSE_DATA } from "@/shared/lib/const";

export async function getHomeCoursesConfig(locale: Locale) {
  const t = await getT(locale);

  return {
    title: t("home.coursesSection.title"),
    list: [
      {
        id: COURSE_DATA.web_development.key,
        title: t("home.coursesSection.list.0.title"),
        description: t("home.coursesSection.list.0.description"),
        duration: t("home.coursesSection.list.0.duration"),
        level: "beginner",
        format: "offline",
        icon: "Code2",
        theme: "blue",
        href: `${siteConfig.routes.courses}/${COURSE_DATA.web_development.key}`,
      },
      {
        id: COURSE_DATA.graphic_design.key,
        title: t("home.coursesSection.list.1.title"),
        description: t("home.coursesSection.list.1.description"),
        duration: t("home.coursesSection.list.1.duration"),
        level: "beginner",
        format: "offline",
        icon: "Palette",
        theme: "rose",
        href: `${siteConfig.routes.courses}/${COURSE_DATA.graphic_design.key}`,
      },
      {
        id: COURSE_DATA.scratch.key,
        title: t("home.coursesSection.list.2.title"),
        description: t("home.coursesSection.list.2.description"),
        duration: t("home.coursesSection.list.2.duration"),
        level: "beginner",
        format: "offline",
        icon: "Puzzle",
        theme: "orange",
        href: `${siteConfig.routes.courses}/${COURSE_DATA.scratch.key}`,
      },
      {
        id: COURSE_DATA.smm.key,
        title: t("home.coursesSection.list.3.title"),
        description: t("home.coursesSection.list.3.description"),
        duration: t("home.coursesSection.list.3.duration"),
        level: "beginner",
        format: "offline",
        icon: "Megaphone",
        theme: "cyan",
        href: `${siteConfig.routes.courses}/${COURSE_DATA.smm.key}`,
      },
      {
        id: COURSE_DATA.python.key,
        title: t("home.coursesSection.list.4.title"),
        description: t("home.coursesSection.list.4.description"),
        duration: t("home.coursesSection.list.4.duration"),
        level: "beginner",
        format: "offline",
        icon: "Workflow",
        theme: "lime",
        href: `${siteConfig.routes.courses}/${COURSE_DATA.python.key}`,
      },
      {
        id: COURSE_DATA.android.key,
        title: t("home.coursesSection.list.5.title"),
        description: t("home.coursesSection.list.5.description"),
        duration: t("home.coursesSection.list.5.duration"),
        level: "beginner",
        format: "offline",
        icon: "Smartphone",
        theme: "emerald",
        href: `${siteConfig.routes.courses}/${COURSE_DATA.android.key}`,
      },
      {
        id: COURSE_DATA.ui_ux.key,
        title: t("home.coursesSection.list.6.title"),
        description: t("home.coursesSection.list.6.description"),
        duration: t("home.coursesSection.list.6.duration"),
        level: "beginner",
        format: "offline",
        icon: "LayoutDashboard",
        theme: "fuchsia",
        href: `${siteConfig.routes.courses}/${COURSE_DATA.ui_ux.key}`,
      },
      {
        id: COURSE_DATA.hr.key,
        title: t("home.coursesSection.list.7.title"),
        description: t("home.coursesSection.list.7.description"),
        duration: t("home.coursesSection.list.7.duration"),
        level: "beginner",
        format: "offline",
        icon: "UsersRound",
        theme: "amber",
        href: `${siteConfig.routes.courses}/${COURSE_DATA.hr.key}`,
      },
      {
        id: COURSE_DATA.soft_skills.key,
        title: t("home.coursesSection.list.8.title"),
        description: t("home.coursesSection.list.8.description"),
        duration: t("home.coursesSection.list.8.duration"),
        level: "beginner",
        format: "offline",
        icon: "MessageSquareText",
        theme: "pink",
        href: `${siteConfig.routes.courses}/${COURSE_DATA.soft_skills.key}`,
      },
    ] as const satisfies readonly Course[],
    levels: {
      beginner: t("home.coursesSection.levels.beginner"),
      intermediate: t("home.coursesSection.levels.intermediate"),
      advanced: t("home.coursesSection.levels.advanced"),
    },
    formats: {
      online: t("home.coursesSection.formats.online"),
      offline: t("home.coursesSection.formats.offline"),
      hybrid: t("home.coursesSection.formats.hybrid"),
    },
  } as const;
}
