import { getT } from "@/shared/lib/i18n";
import type { Locale } from "@/shared/lib/i18n";
import type { Course } from "@/widgets/Courses/types";

export async function getHomeCoursesConfig(locale: Locale) {
  const t = await getT(locale);

  return {
    title: t("home.coursesSection.title"),
    courses: [
      {
        id: "web-development",
        title: t("home.coursesSection.list.0.title"),
        description: t("home.coursesSection.list.0.description"),
        duration: t("home.coursesSection.list.0.duration"),
        level: "beginner",
        format: "offline",
        icon: "Code",
        theme: "blue",
        href: "/courses/web-development",
      },
      {
        id: "graphic-design",
        title: t("home.coursesSection.list.1.title"),
        description: t("home.coursesSection.list.1.description"),
        duration: t("home.coursesSection.list.1.duration"),
        level: "beginner",
        format: "offline",
        icon: "Palette",
        theme: "rose",
        href: "/courses/graphic-design",
      },
      {
        id: "scratch",
        title: t("home.coursesSection.list.2.title"),
        description: t("home.coursesSection.list.2.description"),
        duration: t("home.coursesSection.list.2.duration"),
        level: "beginner",
        format: "offline",
        icon: "Palette",
        theme: "orange",
        href: "/courses/graphic-design",
      },
      {
        id: "smm-content",
        title: t("home.coursesSection.list.3.title"),
        description: t("home.coursesSection.list.3.description"),
        duration: t("home.coursesSection.list.3.duration"),
        level: "beginner",
        format: "offline",
        icon: "Megaphone",
        theme: "cyan",
        href: "/courses/smm-content",
      },
      {
        id: "ai-fundamentals",
        title: t("home.coursesSection.list.4.title"),
        description: t("home.coursesSection.list.4.description"),
        duration: t("home.coursesSection.list.4.duration"),
        level: "beginner",
        format: "offline",
        icon: "Brain",
        theme: "lime",
        href: "/courses/ai-fundamentals",
      },
      {
        id: "android-development",
        title: t("home.coursesSection.list.5.title"),
        description: t("home.coursesSection.list.5.description"),
        duration: t("home.coursesSection.list.5.duration"),
        level: "beginner",
        format: "offline",
        icon: "Smartphone",
        theme: "emerald",
        href: "/courses/android-development",
      },
      {
        id: "ui-ux",
        title: t("home.coursesSection.list.6.title"),
        description: t("home.coursesSection.list.6.description"),
        duration: t("home.coursesSection.list.6.duration"),
        level: "beginner",
        format: "offline",
        icon: "Brain",
        theme: "fuchsia",
        href: "/courses/ai-fundamentals",
      },
      {
        id: "hr",
        title: t("home.coursesSection.list.7.title"),
        description: t("home.coursesSection.list.7.description"),
        duration: t("home.coursesSection.list.7.duration"),
        level: "beginner",
        format: "offline",
        icon: "Brain",
        theme: "amber",
        href: "/courses/ai-fundamentals",
      },
      {
        id: "soft-skills",
        title: t("home.coursesSection.list.8.title"),
        description: t("home.coursesSection.list.8.description"),
        duration: t("home.coursesSection.list.8.duration"),
        level: "beginner",
        format: "offline",
        icon: "Users",
        theme: "pink",
        href: "/courses/soft-skills",
      },
    ] as const satisfies readonly Course[],
    levels: {
      beginner: t("home.coursesSection.levels.beginner"),
      intermediate: t("home.coursesSection.levels.intermediate"),
      advanced: t("home.coursesSection.levels.advanced"),
    },
    formats: {
      online: t("home.coursesSection.formats.online"),
      offline: t("home.coursesSection.formats.offline"),
      hybrid: t("home.coursesSection.formats.hybrid"),
    },
  } as const;
}
